sudo: true
dist: trusty
install: true
language: ruby
rvm:
  - 2.3

services:
  - docker

jobs:
  include:
    - stage: rake build
      install: skip
      script:
      - docker run -v $PWD:/tf-test/module --rm microsoft/terraform-test rake -f ../Rakefile build
    - stage: rake e2e
      install: skip
      script:
      - ssh-keygen -t rsa -b 2048 -C "terraform@microsoft" -P temppass -f /home/travis/id_rsa && docker run -v /home/travis/id_rsa:/root/id_rsa -v $PWD:/tf-test/module -e ARM_CLIENT_ID -e ARM_TENANT_ID -e ARM_SUBSCRIPTION_ID -e ARM_CLIENT_SECRET -e ARM_TEST_LOCATION -e ARM_TEST_LOCATION_ALT --rm microsoft/terraform-test rake -f ../Rakefile e2e